### ISSUE TITLE
Any plans on making the repo more ergonomic as a CMake dependency?

### ISSUE THREAD

**Issue by Falkgaard** [YaaZ/VulkanMemoryAllocator-Hpp#9]
Hi, first of all, thank you for these C++ bindings! I'm wondering if you have any plans of making the repo more CMake-compatible? (Either by making it fetch Vma and run the generator when the dependency is fetched and built or by adding branches with pre-generated headers for corresponding VkHpp semantic versions that can be pulled instead of having to run the generator).

At the moment, my project's CMakeLists.txt has a structure like this:

```cmake
# ...

include( cmake/CPM.cmake )
# ...
CPMAddPackage( "gh:KhronosGroup/Vulkan-Headers@1.3.220" )
CPMAddPackage( "gh:GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator@3.0.1" )

target_link_libraries( ${PROJECT_NAME} PRIVATE
   # ...
   Vulkan::Headers
   VulkanMemoryAllocator
)
```

Which generally lends itself to dependencies being handled in an ergonomic manner (~2 lines per dependency) that provides cloning, building, etc as needed during building. But currently there doesn't seem to be any simple way of adding a VmaHpp dependency since it would rely on having to run the generator would result in a lot of additional complexity overhead in CMakeLists.txt, I'd imagine.

Ideally I think a lot of users would like to be able to just do something like this:

```cmake
# ...

include( cmake/CPM.cmake )
# ...
CPMAddPackage( "gh:KhronosGroup/Vulkan-Headers@1.3.220" )
CPMAddPackage( "gh:YaaZ/VulkanMemoryAllocator-Hpp#target-1.3.220" )

target_link_libraries( ${PROJECT_NAME} PRIVATE
   # ...
   Vulkan::Headers
   VulkanMemoryAllocator-Hpp # or whatever it's called
)
```

where the branch contains generated headers for a VkHpp target version and a CMakeLists.txt that pulls in the appropriate Vma dependency. This would make life so much easier for dumb end-users like me... 🥲

Alternatively if you know of some Modern CMake project that uses `add_custom_command` or `execute_process` and what not to run the generator when needed and cleanly integrating Vma + the built VmaVk as dependencies I'd love to see it so that I can attempt to gleam some insight from it. 🙏 (Sadly a lot of more advanced CMake is still beyond my depth...)

**Comment by YaaZ** [comment]
Hi @Falkgaard! The idea was that the end user wouldn't have to run the generator at all. I assumed that Vulkan-Hpp and VMA API wouldn't change very rapidly, so just releasing updates together with VMA would be enough. Not to mention that bringing Java as a dependency to build some C++ project is a bad idea.

I believe managing compatibility with the wide range of versions of Vulkan-Hpp and VMA is difficult, because generator script itself changes and will not work with old Vulkan-Hpp, for exanple. So why do you need to run the generator at all? Doesn't pre-generated headers work for you?

Anyway,  if there's some way to ease the setup, I'm all for it, I'm just not sure running the generator on user machine is the right way.

**Comment by YaaZ** [comment]
Addressed in this PR: https://github.com/YaaZ/VulkanMemoryAllocator-Hpp/pull/13
